server:
  info:
    project: app
    name: gateway.interface
  http:
    addr: 0.0.0.0:9001
    timeout: 5s
  tracer:
    jaeger:
      endpoint: http://127.0.0.1:14268/api/traces
auth:
  jwt:
    key: app
    issue: panco
data:
  consul:
    address: 127.0.0.1:8500