server:
  http:
    addr: 0.0.0.0:9001
    timeout: 1s
  tracer:
    jaeger:
      endpoint: http://127.0.0.1:14268/api/traces
auth:
  jwt:
    key: demo
    issue: panco
data:
  consul:
    address: 127.0.0.1:8500