server:
  info:
    project: app
    name: user.service
  grpc:
    addr: 0.0.0.0:9002
    timeout: 5s
  tracer:
    jaeger:
      endpoint: http://127.0.0.1:14268/api/traces
auth:
  jwt:
    key: app
    issue: panco
data:
  mysql:
    source: root:0825@tcp(127.0.0.1:3306)/hi_friend?parseTime=True
    max_idle_conn: 10
    max_open_conn: 100
    log_level: 0
    conn_lifetime: 3600s
  consul:
    address: 127.0.0.1:8500