server:
  http:
    addr: 0.0.0.0:9001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  mysql:
    source: root:0825@tcp(127.0.0.1:3306)/hi_friend
    max_idle_conn: 3
    max_open_conn: 10
    log_level: 4
    conn_lifetime: 3600s