server:
  http:
    addr: 0.0.0.0:9001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9002
    timeout: 1s
data:
  mysql:
    source: root:root@tcp(127.0.0.1:3306)/hifriend
    max_idle_conn: 3
    max_open_conn: 10
    log_level: 0
    conn_lifetime: 3600s
  consul:
    address: 192.168.129.156:8500